### PR TITLE
Cybereason: Fix for reported issue - Ungroup Malwares from Splunk SOAR

### PR DESCRIPTION
**Pull request by ritesh-metron**
## Release Notes
- Changed the Malware polling feature to ungroup Malwares with same GUID, but different timestamp

## What is the current behavior?
- Currently the app, when polling for Malwares, groups them based on their GUID's.

## What is the new behavior?
- The grouping of Malwares is now done based on GUID and Timestamp both.

### CODE REVIEW

**Comment by pzhou-splunk** [comment]
Thank you for your submission! We have a total of 8 PRs open right now, and we are working hard on all of them! We will take a look as soon as we can.

**Comment by mishalp-crest** [comment]
@ritesh-metron 
To solve static failures, can you refer [digital shadows connector file](https://github.com/splunk-soar-connectors/digitalshadows/blob/next/digital_shadows_connector.py#L127) and change the code accordingly ?

**Comment by mishalp-crest** [comment]
> @ritesh-metron To solve static failures, can you refer [digital shadows connector file](https://github.com/splunk-soar-connectors/digitalshadows/blob/next/digital_shadows_connector.py#L127) and change the code accordingly ?

@ritesh-metron Any update on this?

**Comment by ritesh-metron** [comment]
@mishalp-crest
Done with the changes. Please take it forward

**Comment by mishalp-crest** [comment]
@ritesh-metron 
As we don’t have write access for source branch 
We have added the required standard changes in #7 along with the existing code of this PR
hence, closing this PR

**Pull request closed without merging**
